### ISSUE TITLE
Please update the folders under graphics export

### ISSUE THREAD

**Issue by nzackoya** [Yayapp/yayapp#35]

**Comment by miguelnarayan** [comment]
Folder updated. Also added 4 pictures that include: font size, color, graphic colors. 
Additionally, here is a color picker, should I have missed anything. http://html-color-codes.info/colors-from-image/

Feel free to ask for anything.

**Comment by nzackoya** [comment]
please add
1. female and male buttons without backgound
2. category photos make just photos without rounded corners

**Comment by miguelnarayan** [comment]
Updated 1 & 2 and others we had discussed.
