### ISSUE TITLE
Twitter Login popup should be responsive

### ISSUE THREAD

**Issue by valentinchka** [Yayapp/yayapp#43]
Description:  Twitter Login popup should be responsive
Steps:
Launch the app
Click Login button
Click Twitter icon 
Enter invalid username and password and click ok
Observe login popup window
Actual Result: Login form should be responsive.  
Device: IPhone 6, ios 8.4.1
<img width="645" alt="screenshot at 06 12-22-53" src="https://cloud.githubusercontent.com/assets/10683727/9703660/2e3b56d0-5493-11e5-9c7c-fded3d9baa2f.png">

**Comment by nzackoya** [comment]
it is on twitter side
