### ISSUE TITLE
Age preferences works unstable

### ISSUE THREAD

**Issue by valentinchka** [Yayapp/yayapp#46]
Description: Age preferences works unstable
Steps:
Launch the app
Login to the app
Click + icon to create a new event
Add photo, Pick category “sport”, pick some nearby location, pic tomorrow’s date, add description
Start moving age preferences icons
Actual Result: Icons are unstable. First time it is moving the second time it isn’t
Device: IPhone 6, ios 8.4.1
Comment: Please ask me if you need video

**Comment by nzackoya** [comment]
could not reproduce
