### ISSUE TITLE
Login/Sign Up page goes up during the entering data

### ISSUE THREAD

**Issue by valentinchka** [Yayapp/yayapp#49]
Description: Login/Sign Up page goes up during the entering data
Steps
Launch the app
Click Login button
Click Email icon 
Click Sign In link / Sign Up link
Start entering value and observe that page goes up
Actual Result: page goes up when start typing
Device: IPhone 6, ios 8.4.1
<img width="547" alt="screenshot at 06 15-07-05" src="https://cloud.githubusercontent.com/assets/10683727/9704276/f7954bb6-54a8-11e5-839e-5b88a0d5a03f.png">

**Comment by nzackoya** [comment]
Without scrolling the screen when keyboard opened it hides the text fields and the button on iphone 4
![ios simulator screen shot 7 2015 17 44 03](https://cloud.githubusercontent.com/assets/4866869/9719314/ccc07864-558b-11e5-89bd-c25de73f76ea.png)
![ios simulator screen shot 7 2015 17 44 27](https://cloud.githubusercontent.com/assets/4866869/9719313/ccbf039e-558b-11e5-9788-831d6d1e9967.png)
