### ISSUE TITLE
White background should be removed for Invite icon

### ISSUE THREAD

**Issue by valentinchka** [Yayapp/yayapp#60]
Description: White background should be removed for Invite icon
Steps
Launch the app
Login to the app
Swipe to see menu options
Actual Result: White background should be removed for Invite icon
Device: IPhone 6, iOS 8.4.1
<img width="275" alt="6" src="https://cloud.githubusercontent.com/assets/10683727/9706547/77d3cfea-54f0-11e5-9d46-e4cc1d142978.png">

**Comment by miguelnarayan** [comment]
Done.
