### ISSUE TITLE
 Possibility to enter code without switching to the new field

### ISSUE THREAD

**Issue by valentinchka** [Yayapp/yayapp#68]
Description: Possibility to enter code without switching to the new field
Steps:
Launch the app
Click Sign Up button
Fill in all fields and wait for invitation code page
Start typing code
Actual Result: Should be possible to enter code without switching to the new field.

**Comment by valentinchka** [comment]
@nzackoya 
Steps:
Launch the app
Click Sign Up button
Fill in all fields and wait for invitation code page
Type code
Start typing code
Actual Result: app crashed. Impossible to open application. One option is reinstalling

**Comment by nzackoya** [comment]
can't reproduce

**Comment by valentinchka** [comment]
It reproduced. See video https://drive.google.com/file/d/0B_HHZD0iwW6ybHlNaUF1LTFtdmxnZ1UtUWI3R0lvdTI4SXdB/view?usp=sharing
