### ISSUE TITLE
There is no option to choose profile photo from library

### ISSUE THREAD

**Issue by valentinchka** [Yayapp/yayapp#70]
Description: There is no option to choose profile photo from library
Steps:
Launch the app
Login to the app
Go to Profile menu option
Click edit icon to edit profile info
Click on the profile image to change photo 
Actual Result: There is no option to choose profile photo from library

**Comment by valentinchka** [comment]
@nzackoya Impossible to make a photo for profile image.
Steps:
1. Launch the app
2. Login to the app
3. Swipe and choose Profile menu option
4. Click edit icon and choose Take Photo
5. Make photo and set it to the user
Actual result:
After user makes a photo the app holds and impossible to do any actions.

**Comment by nzackoya** [comment]
can't reproduce
